package com.example.GeekShop.model.order;

public enum RegionOfCountry {
    Crimea,
    Vinnytsia_region,
    Volyn_region,
    Dnipropetrovsk_region,
    Donetsk_region,
    Zhytomyr_region,
    Transcarpathian_region,
    Zaporizhzhia_region,
    Kirovohrad_region,
    Kyiv_region,
    Bukovel_resort,
    Luhansk_region,
    Lviv_region,
    Mykolaiv_region,
    Odesa_region,
    Poltava_region,
    Rivne_region,
    Sumy_region,
    Ternopil_region,
    Kharkiv_region,
    Kherson_region,
    Khmelnytskyi_region,
    Cherkasy_region,
    Chernivtsi_region,
    Chernihiv_region,
}
